export const openApiDocument = {
  openapi: '3.0.3',
  info: {
    title: 'IRIS To-Do API',
    version: '1.0.0',
    description: 'API test iris-to_to_list',
  },
  servers: [{ url: 'http://localhost:3000/api', description: 'Local' }, { url: 'https://iris-to-do.onrender.com/api', description: 'Producción' }],
  components: {
    securitySchemes: {
      authCookie: { type: 'apiKey', in: 'cookie', name: 'iris_auth', description: 'HttpOnly cookie issued by /auth/login or /auth/register.' },
    },
    schemas: {
      User: { type: 'object', required: ['id', 'fullName', 'email'], properties: { id: { type: 'string' }, fullName: { type: 'string' }, email: { type: 'string', format: 'email' } } },
      AuthResponse: { type: 'object', required: ['data'], properties: { data: { type: 'object', required: ['user'], properties: { user: { $ref: '#/components/schemas/User' } } } } },
      Task: { type: 'object', required: ['id', 'title', 'category', 'priority', 'completed', 'visible', 'dateLimit', 'deletedAt', 'createdAt', 'updatedAt'], properties: { id: { type: 'string' }, userId: { type: 'string' }, title: { type: 'string' }, category: { type: 'string', enum: ['FrontEnd', 'BackEnd', 'Docs'] }, priority: { type: 'string', enum: ['Baja', 'Media', 'Urgente'] }, completed: { type: 'boolean' }, visible: { type: 'boolean' }, dateLimit: { type: 'string', format: 'date', nullable: true }, deletedAt: { type: 'string', format: 'date-time', nullable: true }, createdAt: { type: 'string', format: 'date' }, updatedAt: { type: 'string', format: 'date' } } },
      CreateTaskRequest: { type: 'object', required: ['title', 'category', 'priority'], additionalProperties: false, properties: { title: { type: 'string', minLength: 1, maxLength: 200 }, category: { type: 'string', enum: ['FrontEnd', 'BackEnd', 'Docs'] }, priority: { type: 'string', enum: ['Baja', 'Media', 'Urgente'] }, completed: { type: 'boolean' }, dateLimit: { type: 'string', format: 'date', nullable: true } } },
      UpdateTaskRequest: { type: 'object', minProperties: 1, additionalProperties: false, properties: { title: { type: 'string', minLength: 1, maxLength: 200 }, category: { type: 'string', enum: ['FrontEnd', 'BackEnd', 'Docs'] }, priority: { type: 'string', enum: ['Baja', 'Media', 'Urgente'] }, completed: { type: 'boolean' }, dateLimit: { type: 'string', format: 'date', nullable: true } } },
      Error: { type: 'object', required: ['error'], properties: { error: { type: 'object', required: ['code', 'message'], properties: { code: { type: 'string' }, message: { type: 'string' }, details: {} } } } },
    },
  },
  paths: {
    '/auth/register': { post: { summary: 'Register a user and issue an auth cookie', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false, required: ['fullName', 'email', 'password'], properties: { fullName: { type: 'string', minLength: 2, maxLength: 100, pattern: '^\\p{L}+(?: +\\p{L}+)*$' }, email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 8, maxLength: 128 } } } } } }, responses: { '201': { description: 'User registered', content: { 'application/json': { schema: { $ref: '#/components/schemas/AuthResponse' } } } }, '400': { description: 'Validation error', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, '409': { description: 'Email already exists' } } } },
    '/auth/login': { post: { summary: 'Authenticate a user and issue an auth cookie', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', additionalProperties: false, required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', minLength: 8, maxLength: 128 } } } } } }, responses: { '200': { description: 'User authenticated', headers: { 'Set-Cookie': { description: 'HttpOnly iris_auth cookie', schema: { type: 'string' } } }, content: { 'application/json': { schema: { $ref: '#/components/schemas/AuthResponse' } } } }, '401': { description: 'Invalid credentials' } } } },
    '/auth/me': { get: { summary: 'Get the authenticated user', security: [{ authCookie: [] }], responses: { '200': { description: 'Current user', content: { 'application/json': { schema: { $ref: '#/components/schemas/AuthResponse' } } } }, '401': { description: 'Authentication required' } } } },
    '/auth/logout': { post: { summary: 'Clear the auth cookie', responses: { '204': { description: 'Session closed' } } } },
    '/tasks': { get: { summary: 'List tasks for the authenticated user', security: [{ authCookie: [] }], parameters: [{ name: 'completed', in: 'query', schema: { type: 'boolean' } }, { name: 'visible', in: 'query', schema: { type: 'boolean', default: true } }, { name: 'page', in: 'query', schema: { type: 'integer', minimum: 1, default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 } }], responses: { '200': { description: 'Task list' }, '401': { description: 'Authentication required' } } }, post: { summary: 'Create a task for the authenticated user', security: [{ authCookie: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/CreateTaskRequest' } } } }, responses: { '201': { description: 'Task created' }, '400': { description: 'Validation error' }, '401': { description: 'Authentication required' } } } },
    '/tasks/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-fA-F0-9]{24}$' } }], get: { summary: 'Get a task owned by the authenticated user', security: [{ authCookie: [] }], responses: { '200': { description: 'Task found' }, '401': { description: 'Authentication required' }, '404': { description: 'Task not found' } } }, patch: { summary: 'Update a task owned by the authenticated user', security: [{ authCookie: [] }], requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/UpdateTaskRequest' } } } }, responses: { '200': { description: 'Task updated' }, '400': { description: 'Validation error' }, '404': { description: 'Task not found' } } }, delete: { summary: 'Move a task to the trash', security: [{ authCookie: [] }], responses: { '204': { description: 'Task moved to trash' }, '404': { description: 'Task not found' } } } },
    '/tasks/{id}/restore': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', pattern: '^[a-fA-F0-9]{24}$' } }], post: { summary: 'Restore a task from the trash', security: [{ authCookie: [] }], responses: { '200': { description: 'Task restored' }, '404': { description: 'Task not found in trash' } } } },
  },
} as const;
